"""create initial tables

Revision ID: f24972e8b68b
Revises: 
Create Date: 2026-07-04 13:14:21.446184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f24972e8b68b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('phone_num', sa.String(length=20), nullable=True),
    sa.Column('email_id', sa.String(length=255), nullable=True),
    sa.Column('user_status', sa.Enum('ACTIVE', 'IN-ACTIVE', name='ck_users_user_status', native_enum=False, length=20), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_name', sa.String(length=200), nullable=False),
    sa.Column('group_desc', sa.String(length=1000), nullable=True),
    sa.Column('group_category', sa.String(length=100), nullable=False),
    sa.Column('group_status', sa.Enum('ACTIVE', 'IN-ACTIVE', name='ck_groups_group_status', native_enum=False, length=20), server_default='ACTIVE', nullable=False),
    sa.Column('group_icon_url', sa.String(length=500), nullable=True),
    sa.Column('group_creater_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_creater_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_group_creater_id'), 'groups', ['group_creater_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_title', sa.String(length=200), nullable=False),
    sa.Column('task_desc', sa.String(length=2000), nullable=True),
    sa.Column('task_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('task_state', sa.Enum('TODO', 'IN-PROGRESS', 'COMPLETED', name='ck_tasks_task_state', native_enum=False, length=20), server_default='TODO', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_created_by'), 'tasks', ['created_by'], unique=False)
    op.create_index(op.f('ix_tasks_updated_by'), 'tasks', ['updated_by'], unique=False)
    op.create_table('group_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('assignee_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'group_id', name='uq_group_tasks_task_id_group_id')
    )
    op.create_index(op.f('ix_group_tasks_assignee_id'), 'group_tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_group_tasks_group_id'), 'group_tasks', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_tasks_task_id'), 'group_tasks', ['task_id'], unique=False)
    op.create_table('user_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('relationship', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', name='uq_user_groups_user_id_group_id')
    )
    op.create_index(op.f('ix_user_groups_group_id'), 'user_groups', ['group_id'], unique=False)
    op.create_index(op.f('ix_user_groups_user_id'), 'user_groups', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_groups_user_id'), table_name='user_groups')
    op.drop_index(op.f('ix_user_groups_group_id'), table_name='user_groups')
    op.drop_table('user_groups')
    op.drop_index(op.f('ix_group_tasks_task_id'), table_name='group_tasks')
    op.drop_index(op.f('ix_group_tasks_group_id'), table_name='group_tasks')
    op.drop_index(op.f('ix_group_tasks_assignee_id'), table_name='group_tasks')
    op.drop_table('group_tasks')
    op.drop_index(op.f('ix_tasks_updated_by'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_by'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_groups_group_creater_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_table('users')
    # ### end Alembic commands ###
